name: ci-android

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK: "/usr/local/lib/android/sdk/ndk/24.0.8215888"
      ANDROID_NDK_HOME: "/usr/local/lib/android/sdk/ndk/24.0.8215888"
      ANDROID_NDK_LATEST_HOME: "/usr/local/lib/android/sdk/ndk/24.0.8215888"
      ANDROID_NDK_ROOT: "/usr/local/lib/android/sdk/ndk/24.0.8215888"
    steps:
    - uses: actions/checkout@v3

    - name: Configure environment
      run: |
        sudo apt install -y git build-essential ninja-build

    - name: Install vcpkg and dependencies
      run: |
        # Install dependencies
        TRIPLETS="arm-neon-android arm64-android x86-android x64-android"

        pushd $VCPKG_INSTALLATION_ROOT

        for TRIPLET in $TRIPLETS
        do
          echo "Install dependencies for $TRIPLET"
          ./vcpkg install "libjpeg-turbo:$TRIPLET"
          ./vcpkg install "stb:$TRIPLET"
          ./vcpkg install "libwebp:$TRIPLET"
        done

        popd

    - name: Build (Android)
      run: |
        CFG_FLAGS=('-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}' '-DVCPKG_CMAKE_SYSTEM_NAME=Android' '-DCMAKE_SYSTEM_NAME=Android' "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake")

        TRIPLET='arm-neon-android'
        ABI='armeabi-v7a'
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DANDROID_ABI=$ABI "${CFG_FLAGS[@]}"
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

        TRIPLET='arm64-android'
        ABI='arm64-v8a'
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DANDROID_ABI=$ABI "${CFG_FLAGS[@]}"
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

        TRIPLET='x86-android'
        ABI='x86'
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DANDROID_ABI=$ABI "${CFG_FLAGS[@]}"
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

        TRIPLET='x64-android'
        ABI='x86_64'
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DANDROID_ABI=$ABI "${CFG_FLAGS[@]}"
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

    - name: Upload Artifact (arm-android)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-arm-neon-android.so
        path: ${{github.workspace}}/build-arm-neon-android/libUnimage.so

    - name: Upload Artifact (arm64-android)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-arm64-android.so
        path: ${{github.workspace}}/build-arm64-android/libUnimage.so

    - name: Upload Artifact (x86-android)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x86-android.so
        path: ${{github.workspace}}/build-x86-android/libUnimage.so

    - name: Upload Artifact (x64-android)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x64-android.so
        path: ${{github.workspace}}/build-x64-android/libUnimage.so
