name: ci-linux

on: workflow_dispatch


env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure environment
      run: |
        sudo apt install -y git build-essential

    - name: Install vcpkg and dependencies
      run: |
        # Install dependencies
        TRIPLETS="x64-linux arm64-linux"

        pushd $VCPKG_INSTALLATION_ROOT

        for TRIPLET in $TRIPLETS
        do
          echo "Install dependencies for $TRIPLET"
          ./vcpkg install "libjpeg-turbo:$TRIPLET"
          ./vcpkg install "stb:$TRIPLET"
          ./vcpkg install "libwebp:$TRIPLET"
        done

        popd

    - name: Configure and build
      run: |
        TRIPLET="x64-linux"
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

        TRIPLET="arm64-linux"
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

    - name: Upload Artifact (x64-linux)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x64-linux.so
        path: ${{github.workspace}}/build-x64-linux/libUnimage.so
        
    - name: Upload Artifact (arm64-linux)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-arm64-linux.so
        path: ${{github.workspace}}/build-arm64-linux/libUnimage.so