name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  TRIPLET: x64-linux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure environment
      run: |
        sudo apt install -y git build-essential make
        export TRIPLET=${{env.TRIPLET}}
      
    - name: Install vcpkg and dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg
        pushd vcpkg
        export VCPKG_DIR=$(pwd)
        ./bootstrap-vcpkg.sh
        ./vcpkg install "libjpeg-turbo:$TRIPLET"
        ./vcpkg install "stb:$TRIPLET"
        ./vcpkg install "libwebp:$TRIPLET"
        popd

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=$VCPKG_DIR/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload libUnimage.so
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage.so
        path: ${{github.workspace}}/build/libUnimage.so

