name: ci-linux

on: workflow_dispatch


env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure environment
      run: |
        sudo apt install -y git build-essential

    - name: Install vcpkg and dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg
        pushd vcpkg
        # Install vcpkg
        echo "Install vcpkg"
        ./bootstrap-vcpkg.sh

        # Install dependencies
        TRIPLET="x64-linux"
        ./vcpkg install "libjpeg-turbo:$TRIPLET"
        ./vcpkg install "stb:$TRIPLET"
        ./vcpkg install "libwebp:$TRIPLET"

        popd

    - name: Configure CMake
      run: |
        TRIPLET="x64-linux"
        cmake -B ${{github.workspace}}/build-$TRIPLET -DVCPKG_TARGET_TRIPLET=$TRIPLET -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake


    - name: Build
      run: |
        TRIPLET="x64-linux"
        cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}

    - name: Upload Artifact (x64-linux)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x64-linux.so
        path: ${{github.workspace}}/build-x64-linux/libUnimage.so
