name: ci-win

on: workflow_dispatch


env:
  BUILD_TYPE: Release

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install vcpkg and dependencies, then configure and build it
      run: |
        $VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT;

        # Install dependencies and build
        $TRIPLETS='x64-windows';
        foreach ($TRIPLET in $TRIPLETS) {
          echo "Install dependencies for $TRIPLET"
          pushd $VCPKG_ROOT
          ./vcpkg install "libjpeg-turbo:$TRIPLET"
          ./vcpkg install "stb:$TRIPLET"
          ./vcpkg install "libwebp:$TRIPLET"
          popd

          echo "Build for $TRIPLET"
          cmake -B ${{github.workspace}}/build-$TRIPLET -A x64 -DVCPKG_TARGET_TRIPLET=$TRIPLET "-DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake --build ${{github.workspace}}/build-$TRIPLET --config ${{env.BUILD_TYPE}}
        }

    - name: Upload Artifact (x64-windows)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x64-windows.dll
        path: ${{github.workspace}}/build-x64-windows/libUnimage.dll

    - name: Upload Artifact (x86-windows)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: libUnimage-x86-windows.dll
        path: ${{github.workspace}}/build-x86-windows/libUnimage.dll


